[package]
name = "ratson"
version = "0.1.0"
authors = ["Rasmus Larsen <doctorherbstein@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
structopt = "0.3.21"
